test Rcpp

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,20 +1,30 @@
-#! /bin/bash
+#! /bin/sh
 # Copyright (c) 2017-2023 King Abdullah University of Science and Technology,
 # All rights reserved.
 # ExaGeoStat is a software package, provided by King Abdullah University of Science and Technology (KAUST).
 
 # @file config.sh
 # @version 1.1.0
-# @author David Helmy
 # @author Mahmoud ElKarargy
-# @date 2024-01-15
+# @author David Helmy
+# @date 2024-02-04
 
+# Set variables and default values
+RED='\033[0;31m'
+GREEN='\033[0;32m'
+YELLOW='\033[0;33m'
+BLUE='\033[0;34m'
+NC='\033[0m'
+
+# shellcheck disable=SC2164
 cd "$(dirname "$0")"
+# Get the operating system type using uname
+OS_TYPE=$(uname)
 
-if [[ "$OSTYPE" == "darwin"* ]]; then
+if [ "$OS_TYPE" = "darwin"* ]; then
   ABSOLUTE_PATH=$([[ $1 == /* ]] && echo "$1" || echo "$PWD/${1#./}")
 else
-  ABSOLUTE_PATH=$(dirname $(realpath "$0"))
+  ABSOLUTE_PATH=$(dirname "$(realpath "$0")")
 fi
 
 INSTALL_PREFIX=$PWD/installdir/_deps
@@ -30,10 +40,133 @@ PACKAGE="OFF"
 COMPILE_FLAGS="-Wl,--no-as-needed -w -fpic"
 DEVELOPER_WARNINGS="-Wno-dev"
 
+# Parse command line options
+while getopts ":tevhHi:cmspTwr" opt; do
+  case $opt in
+  i) ##### Define installation path  #####
+    echo "${YELLOW}Installation path set to $OPTARG.${NC}"
+    INSTALL_PREFIX=$OPTARG
+    ;;
+  t) ##### Building tests enabled #####
+    echo "${GREEN}Building tests enabled.${NC}"
+    BUILDING_TESTS="ON"
+    ;;
+  T) ##### Building heavy tests enabled #####
+    echo "${GREEN}Building heavy tests enabled.${NC}"
+    BUILDING_HEAVY_TESTS="ON"
+    ;;
+  e) ##### Building examples enabled #####
+    echo "${GREEN}Building examples enabled.${NC}"
+    BUILDING_EXAMPLES="ON"
+    ;;
+  H) ##### Using HiCMA #####
+    echo "${GREEN}Using HiCMA.${NC}"
+    USING_HiCMA="ON"
+    ;;
+  c) ##### Using cuda enabled #####
+    echo "${GREEN}Cuda enabled ${NC}"
+    USE_CUDA="ON"
+    ;;
+  m) ##### Using MPI enabled #####
+    echo "${GREEN}MPI enabled ${NC}"
+    USE_MPI="ON"
+    ;;
+  v) ##### printing full output of make #####
+    echo "${GREEN}printing make with details.${NC}"
+    VERBOSE="ON"
+    ;;
+  s) ##### Passing BLA vendor with mkl #####
+    echo "${GREEN}MKL as a BLA vendor${NC}"
+    BLAS_VENDOR="Intel10_64lp"
+    ;;
+  p) ##### Enabling packaging system for distribution #####
+    echo "${GREEN}CPACK enabled${NC}"
+    PACKAGE=ON
+    ;;
+  w) ##### Enable showing all the warnings #####
+    echo "${GREEN}Showing Warnings is enabled${NC}"
+    SHOW_WARNINGS="ON"
+    ;;
+  r) ##### Enable R and Rcpp support #####
+    echo "${GREEN}R is enabled${NC}"
+    USE_R="ON"
+    ;;
+  \?) ##### Error unknown option #####
+    echo "Option $OPTARG parameter is unknown, please -h for help"
+    exit 1
+    ;;
+  :) ##### Error in an option #####
+    echo "Option $OPTARG requires parameter(s)"
+    exit 0
+    ;;
+  h) ##### Prints the help #####
+    echo "Usage of $(basename "$0"):"
+    echo ""
+    printf "%20s %s\n" "-i [path] :" "specify installation path, default = ${PWD}/installdir/_deps/"
+    printf "%20s %s\n" "-t :" "to enable building tests."
+    printf "%20s %s\n" "-T :" "to enable building heavy tests."
+    printf "%20s %s\n" "-e :" "to enable building examples."
+    printf "%20s %s\n" "-H :" "to enable using HiCMA."
+    printf "%20s %s\n" "-c :" "to enable using CUDA."
+    printf "%20s %s\n" "-m :" "to enable using MPI."
+    printf "%20s %s\n" "-v :" "to enable verbose printings."
+    printf "%20s %s\n" "-d :" "to enable debug mode."
+    printf "%20s %s\n" "-s :" "to manually pass MKL as your bla vendor."
+    printf "%20s %s\n" "-p :" "to enable a packaging system for distribution."
+    printf "%20s %s\n" "-h :" "Help."
+    echo ""
+    exit 1
+    ;;
+  esac
+done
+
+if [ -z "$BUILDING_TESTS" ]; then
+  BUILDING_TESTS="OFF"
+  echo "${RED}Building tests disabled.${NC}"
+fi
+
+if [ -z "$BUILDING_EXAMPLES" ]; then
+  BUILDING_EXAMPLES="OFF"
+  echo "${RED}Building examples disabled.${NC}"
+fi
+
+echo "${BLUE}Installation path set to $INSTALL_PREFIX.${NC}"
+
+if [ -z "$USING_HiCMA" ]; then
+  echo "${RED}Using HiCMA is disabled.${NC}"
+fi
+
+if [ -z "$USE_CUDA" ]; then
+  USE_CUDA="OFF"
+  echo "${RED}Using CUDA disabled${NC}"
+fi
+
+if [ -z "$USE_MPI" ]; then
+  USE_MPI="OFF"
+  echo "${RED}Using MPI disabled${NC}"
+fi
+
+if [ "$SHOW_WARNINGS" = "ON" ]; then
+  COMPILE_FLAGS="$COMPILE_FLAGS -W"
+  DEVELOPER_WARNINGS=""
+elif [ "$SHOW_WARNINGS" = "OFF" ]; then
+  COMPILE_FLAGS="$COMPILE_FLAGS -w"
+fi
+
+if [ -z "$USE_R" ]; then
+  USE_R="OFF"
+  echo "${RED}Using R is disabled${NC}"
+fi
+
+echo ""
+echo "${YELLOW}Use -h to print the usages of exageostat-cpp flags.${NC}"
+echo ""
+
+# cleaning bin
 rm -rf bin/
 mkdir bin/
 
-cmake $DEVELOPER_WARNINGS -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
+cmake "$DEVELOPER_WARNINGS" -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
   -DCMAKE_BUILD_TYPE=RELEASE \
   -DCMAKE_INSTALL_PREFIX="${INSTALL_PREFIX}" \
   -DBUILD_TESTS="${BUILDING_TESTS}" \
@@ -43,7 +176,7 @@ cmake $DEVELOPER_WARNINGS -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
   -DCMAKE_VERBOSE_MAKEFILE:BOOL=${VERBOSE} \
   -DUSE_CUDA="${USE_CUDA}" \
   -DUSE_MPI="${USE_MPI}" \
-  -DUSE_R=ON \
+  -DUSE_R="${USE_R}" \
   -DBLA_VENDOR="${BLAS_VENDOR}" \
   -DCREATE_PACKAGE="${PACKAGE}" \
   -DBUILD_SHARED_LIBS=OFF \
@@ -53,19 +186,22 @@ cmake $DEVELOPER_WARNINGS -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
   -DCMAKE_CXX_FLAGS_DEBUG="$COMPILE_FLAGS" \
   -DCMAKE_CXX_FLAGS_RELEASE="$COMPILE_FLAGS"
 
-# Change to the bin directory, or exit if it doesn't exist.
-cd bin/ || {
-  echo "Error: bin directory not found."
-  exit 1
-}
+if [ "$USE_R" = "ON" ]; then
+  # Change to the bin directory, or exit if it doesn't exist.
+  cd bin/ || {
+    echo "Error: bin directory not found."
+    exit 1
+  }
 
-# Clean the directory and build the code with the specified options.
-cmake --build . -j $(nproc)
+  # Clean the directory and build the code with the specified options.
+  cmake --build . -j "$(nproc)"
 
-if [[ "$OSTYPE" == "darwin"* ]]; then
-  cp "${ABSOLUTE_PATH}/bin/src/libExaGeoStatCPP.dylib" "${ABSOLUTE_PATH}/src/ExaGeoStatCPP.so" || echo "Failed: libExaGeoStatCPP.dylib -> src"
-else
-  cp "${ABSOLUTE_PATH}/bin/src/libExaGeoStatCPP.so" "${ABSOLUTE_PATH}/src/ExaGeoStatCPP.so" || echo "Failed: libExaGeoStatCPP.so -> src"
+  if [ "$OS_TYPE" = "darwin"* ]; then
+    cp "${ABSOLUTE_PATH}/bin/src/libExaGeoStatCPP.dylib" "${ABSOLUTE_PATH}/src/ExaGeoStatCPP.so" || echo "Failed: libExaGeoStatCPP.dylib -> src"
+  else
+    cp "${ABSOLUTE_PATH}/bin/src/libExaGeoStatCPP.so" "${ABSOLUTE_PATH}/src/ExaGeoStatCPP.so" || echo "Failed: libExaGeoStatCPP.so -> src"
+  fi
+
+  rm -rf "${ABSOLUTE_PATH:?}/bin/"*
+
 fi
-
-rm -rf "${ABSOLUTE_PATH}/bin/"
